name: workflow
version: 1
description: "13-Step Contract-First Development Workflow"

artifacts:
  # --- Phase 0: Infrastructure (Optional, for new projects) ---
  - id: infrastructure
    generates: infrastructure.md
    description: "Phase 0: Infrastructure Specification (Optional) - Logging, Error Handling, Middleware"
    template: infrastructure.md
    instruction: |
      Create the infrastructure specification that establishes foundational patterns.
      
      **When to create** (only for new projects or major refactors):
      - New project without existing infrastructure patterns
      - Major changes to logging, error handling, or middleware architecture
      
      **Required Sections**:
      1. **Logging System**
         - Log levels and usage (DEBUG/INFO/WARN/ERROR/CRITICAL)
         - Structured logging format with trace_id support
         - Performance logging for slow operations (>1s)
      
      2. **Error Handling System**
         - Error code structure and categories (1xxx-5xxx)
         - Standard error codes table
         - Error response format with error_details
      
      3. **Request/Response Format**
         - StandardResp structure: `{code, message, data}`
         - Success/Error response examples
         - Pagination response format
         - Required request headers (X-Request-ID)
      
      4. **Middleware Architecture**
         - Middleware components (Auth, Validation, Logging, Error Handler)
         - Execution order (CORS → Request ID → Logging → Auth → Validation → Handler → Response → Error Handler)
      
      5. **Development Mode Support**
         - Frontend-only mode configuration
         - Backend-only mode configuration
         - Fullstack mode configuration
      
      **Note**: This is a one-time setup. Skip if infrastructure.md already exists.
      Reference: context/tech_stack.md for technology choices.
    requires: []

  # --- Phase 1: Definition (Steps 2-4) ---
  - id: proposal
    generates: proposal.md
    description: "Phase 1: Proposal & User Stories (Steps 2-3)"
    template: proposal.md
    instruction: |
      Create the proposal document that establishes WHY this change is needed.
      
      **Required Sections**:
      1. **Background & Goals**
         - What problem does this solve? Why now?
         - Business value and expected outcomes
      
      2. **Non-Goals** (MUST be explicitly defined)
         - What this change will NOT address
         - Scope boundaries
      
      3. **User Stories**
         - As a [user type], I want to [action], so that [benefit]
         - Include acceptance criteria
      
      4. **Edge Cases & Risks** (MUST be explicitly defined)
         - Potential failure scenarios
         - Risk mitigation strategies
      
      5. **Impact**
         - Affected code, APIs, dependencies, or systems
         - Breaking changes (mark with **BREAKING**)
      
      **Language**: Follow project config (zh-CN or en-US)
      **Tech Alignment**: Ensure alignment with context/tech_stack.md
      
      Keep it concise (1-2 pages). Focus on the "why" not the "how".
    requires: []

  # --- Phase 1: Contract/Spec (Step 4) ---
  - id: spec
    generates: spec.md
    description: "Phase 1: Step 4 - API Spec with JSON Examples (Source of Truth)"
    template: spec.md
    instruction: |
      Create the API specification that serves as the **Source of Truth** for this feature.
      
      **Required Sections**:
      1. **Overview**
         - Brief description of the feature's API
      
      2. **API Endpoints** (for each endpoint):
         ```
         ### `METHOD /path`
         **Summary**: endpoint description
         
         **Request**:
         ```json
         { /* request body example */ }
         ```
         
         **Response** (Success):
         ```json
         {
           "code": 0,
           "message": "success",
           "data": { /* response data - MUST follow StandardResp */ }
         }
         ```
         
         **Response** (Error):
         ```json
         {
           "code": 1000,
           "message": "Invalid Parameter",
           "data": null,
           "error_details": { "field": "xxx", "reason": "xxx", "trace_id": "uuid" }
         }
         ```
         
         **Error Codes**: Reference infrastructure.md
         **Logging Requirements**: What to log for this endpoint
         ```
      
      3. **Database Schema** (if applicable):
         - Table definitions with columns, types, nullable
         - Indexes and constraints
         - Seed data examples from JSON responses
      
      4. **Validation Checklist**:
         - [ ] All endpoints have JSON request/response examples
         - [ ] All responses follow StandardResp structure
         - [ ] Database tables define necessary indexes
         - [ ] Error codes follow infrastructure.md standards
         - [ ] Logging requirements specified
      
      **Important**: JSON examples will be used for mock data in Phase 3.
    requires:
      - proposal

  # --- Phase 2: Design Split (Step 5) ---
  - id: design
    generates: design.md
    description: "Phase 2: Step 5 - FE/BE Split Architecture"
    template: design.md
    instruction: |
      Create the design document that explains HOW to implement the change.
      
      **First, determine Development Mode**:
      - **fullstack**: Complete frontend + backend + middleware (default)
      - **frontend-only**: Frontend development with mock backend
      - **backend-only**: Backend API development without frontend
      - **middleware-only**: Middleware/infrastructure development
      
      **Required Sections**:
      
      1. **Development Mode Configuration**
         - Selected mode and rationale
         - Mode-specific considerations
      
      2. **Frontend Architecture** (unless backend-only):
         - Component tree and descriptions
         - State management approach
         - Mocking strategy (use JSON from spec.md)
         - API integration (client, interceptors, error handling)
         - Routing (if applicable)
      
      3. **Backend Architecture** (unless frontend-only):
         - Router location and endpoints
         - Business logic (Service classes, methods)
         - DB operations (tables, queries, transactions)
         - Middleware integration (auth, validation, logging)
         - External dependencies
      
      4. **Middleware Architecture**:
         - Middleware components
         - Execution order
         - Reference infrastructure.md for patterns
      
      5. **Verification Plan**:
         - Unit tests scope
         - Integration tests scope
         - Contract verification approach
      
      6. **Development Workflow** (Phase 3-6 preview):
         - Phase 3: Frontend Mock Dev steps
         - Phase 4: Backend Skeleton steps
         - Phase 5: Contract Testing steps
         - Phase 6: Implementation steps
      
      7. **Infrastructure Integration**:
         - Logging requirements
         - Error handling approach
         - Request/Response format compliance
      
      Reference: spec.md for what to build, infrastructure.md for how to build it.
    requires:
      - spec

  # --- Phase 3-8: Task Breakdown ---
  - id: tasks
    generates: tasks.md
    description: "Phase 3-8: Implementation & Verification Steps (13-Step Workflow)"
    template: tasks.md
    instruction: |
      Generate the task breakdown following the **13-Step Contract-First Workflow**.
      
      **CRITICAL**: Do not use generic descriptions. Replace with SPECIFIC:
      - File paths (e.g., `src/components/UserList.tsx`)
      - Class names (e.g., `UserService`)
      - Function names (e.g., `getUserById()`)
      - Table names (e.g., `users`, `orders`)
      
      **Required Structure** (use exactly this format):
      
      ```markdown
      # Task Tracking: [Feature Name]
      
      ## Phase 0: Initialization (Step 1)
      - [x] **Task 0.1**: [Step 1] Analyze Tech Stack & Map Structure
        - Status: Completed via Context Injection.
      - [ ] **Task 0.2**: [Step 1] Setup Infrastructure Components
        - Action: Review infrastructure.md for foundational patterns
        - Note: Skip if infrastructure already exists.
      
      ## Phase 1: Definition (Steps 2-4)
      - [x] **Task 1.1**: [Step 2] Draft Proposal (Completed in proposal.md)
      - [x] **Task 1.2**: [Step 3] Validate Proposal Logic (User Verified)
      - [x] **Task 1.3**: [Step 4] Define Specs (Completed in spec.md)
      
      ## Phase 2: Design Split (Step 5)
      - [x] **Task 2.1**: [Step 5] Frontend/Backend Design (Completed in design.md)
      
      ## Phase 3: Frontend Mock Dev (Steps 6-7)
      - [ ] **Task 3.1**: [Step 6] Implement Frontend with Mock Data
        - Action: Create Mock Data conforming to StandardResp format
        - Action: Implement UI Components: [list specific components]
        - Action: Implement API client with X-Request-ID
      - [ ] **Task 3.2**: [Step 7] Verify Frontend Features
        - Action: Verify data rendering and interaction
        - Action: Test loading/error/empty states
      
      ## Phase 4: Backend Skeleton (Step 8)
      - [ ] **Task 4.1**: [Step 8] Implement Controller Skeleton
        - Target: [specific router files]
        - Constraint: Return Static JSON from spec.md. NO DB CONNECTION.
        - Action: Implement middleware integration
      
      ## Phase 5: Contract Testing (Step 9)
      - [ ] **Task 5.1**: [Step 9] Run E2E Tests (Mock Mode)
        - Action: Verify response format matches spec.md
        - Action: Test error responses and error codes
      
      ## Phase 6: Implementation (Step 10)
      - [ ] **Task 6.1**: [Step 10] Database Models & Migrations
        - Action: Create migration for tables: [specific tables]
        - Action: Generate Seed Data from spec.md JSON
      - [ ] **Task 6.2**: [Step 10] Implement Service Logic
        - Action: Implement business logic in [specific services]
        - Constraint: Include Structured Logging (trace_id, duration_ms)
      - [ ] **Task 6.3**: [Step 10] Connect Frontend to Real Backend
      
      ## Phase 7: Real Verification (Steps 11-12)
      - [ ] **Task 7.1**: [Step 11] Run Tests (Real DB)
      - [ ] **Task 7.2**: [Step 12] Audit Code vs Spec (Drift Check)
        - Constraint: Drift rate < 1%
      
      ## Phase 8: Archive (Step 13)
      - [ ] **Task 8.1**: [Step 13] Prepare Archive
        - Action: Run `openspec archive`
      
      ## Progress Summary
      | Phase | Status |
      |-------|--------|
      | Phase 0-2 | ✅ Done |
      | Phase 3-8 | ⏳ Pending |
      ```
      
      **Adapt based on dev_mode**:
      - backend-only: Skip frontend tasks
      - frontend-only: Skip backend tasks
      - fullstack: Include all tasks
      
      Reference: spec.md for what to build, design.md for how to build it.
    requires:
      - design
      - spec

apply:
  requires: [tasks]
  tracks: tasks.md
  instruction: |
    Execute the 13-Step Contract-First Workflow tasks.
    
    **Workflow**:
    1. Read all context files (proposal.md, spec.md, design.md, tasks.md)
    2. Work through pending tasks in order (Phase 3 → Phase 8)
    3. Mark tasks complete as you go: `- [x]`
    4. Pause if you hit blockers or need clarification
    
    **Key Constraints**:
    - Phase 3-4: Use mock data from spec.md JSON examples
    - Phase 4: Return static JSON, NO database connection
    - Phase 6: Replace mock with real implementation
    - Phase 7: Verify drift rate < 1%
    
    **Infrastructure Compliance**:
    - All responses follow StandardResp format
    - Include X-Request-ID in requests
    - Use error codes from infrastructure.md
    - Implement structured logging with trace_id
