name: workflow
description: "13-Step Contract-First Development Workflow"

artifacts:
  # --- Phase 0-1: Definition ---
  - name: proposal
    type: markdown
    description: "Phase 1: Proposal & User Stories (Step 1-3)"
    template: "proposal.hbs"

  # --- Phase 1: Contract/Spec (Step 4) ---
  - name: spec
    type: markdown
    extension: "md"
    description: "Phase 1: Step 4 - API Spec with JSON Examples (spec.md)"
    dependencies: ["proposal"]
    template: "contract.hbs"
    rules:
      - "Must include API endpoints with JSON request/response examples."
      - "Must follow 'StandardResp' structure for responses."
      - "Must define database schema with indexes if applicable."

  # --- Phase 2: Design Split (Step 5) ---
  - name: design
    type: markdown
    description: "Phase 2: Step 5 - FE/BE Split Architecture"
    dependencies: ["spec"]
    template: "design.hbs"

  # --- Phase 3-8: Task Breakdown ---
  - name: tasks
    type: tasks
    description: "Phase 3-8: Implementation & Verification Steps"
    dependencies: ["design", "spec"]
    template: "tasks.hbs"
